### ISSUE TITLE
L5 Support

### ISSUE THREAD

**Issue by teslaji** [vishwajeetv/laravel_angular_material#1]
Will you be upgrading this with laravel 5 anytime soon? Thanks

**Comment by vishwajeetv** [comment]
At the time of creation, Laravel 5 didn't have MongoDB driver support.
( Laravel doesn't have built in driver for MongoDB, I used this package for the same - https://github.com/jenssegers/laravel-mongodb )
As this package supports Laravel 5 now, I will update this soon.

**Comment by vishwajeetv** [comment]
@kbhatt2006 BTW you can check out my other project -
https://github.com/vishwajeetv/larangular
This does not use MongoDb, but a very useful starter project with Laravel 5 and AngularJS with Material design

**Comment by teslaji** [comment]
Thanks I'll pull the repo and go through it.
